FROM rocker/shiny-verse:4.2.2

LABEL MAINTAINER Thiago Britto-Borges "thiago.brittoborges@uni-heidelberg.de"

RUN apt-get update \
    && apt-get install -y software-properties-common \
    && add-apt-repository ppa:criu/ppa \
    && apt-get update \
    && apt-get install -y \
    software-properties-common \
    sudo \
    criu \
    pandoc \
    pandoc-citeproc \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev \
    libfftw3-dev \
    libpq-dev \
    libbz2-dev \
    liblzma-dev \
    strace \
    && rm -rf /var/lib/apt/lists/*

# set options
ENV RENV_PATHS_LIBRARY renv/library

RUN useradd app \
    && mkdir /app \
    && chown app /app

ENV RENV_VERSION v1.0.0
RUN R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))"
RUN R -e "remotes::install_github('rstudio/renv@${RENV_VERSION}', force=TRUE)"

